import React, { useState, useEffect } from 'react';
import AdminCrudSection from './AdminCrudSection';
import { Profile, Order, Product, ProductContentBlock, ProductVariant, AppVersion } from '../types';
import { fetchAllOrders, updateOrder, supabase, fetchSiteConfig } from '../services/supabaseService';
import { SITE_CONFIG, LOCAL_INSIGHTS, LOCAL_PRODUCTS, LOCAL_VARIANTS, LOCAL_BLOCKS } from '../services/localRegistry';

type TabType = 'visual_dna' | 'sovereign_store' | 'insights' | 'security_hub' | 'orders' | 'hard_build';

const ADMIN_VERSION = "v14.5-SOVEREIGN-GUARDIAN";

interface AdminDashboardProps {
  onClose: () => void;
  profile: Profile;
}

const AdminDashboard: React.FC<AdminDashboardProps> = ({ onClose, profile }) => {
  const [activeTab, setActiveTab] = useState<TabType>('visual_dna');
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(false);
  const [config, setConfig] = useState(fetchSiteConfig());

  // Estado Local para o Registry Factory (O Frontend Soberano)
  const [registryProducts, setRegistryProducts] = useState<Product[]>(LOCAL_PRODUCTS);
  const [registryVariants, setRegistryVariants] = useState<Record<string, ProductVariant[]>>(LOCAL_VARIANTS);
  const [registryBlocks, setRegistryBlocks] = useState<Record<string, ProductContentBlock[]>>(LOCAL_BLOCKS);
  const [selectedProductId, setSelectedProductId] = useState<string | null>(LOCAL_PRODUCTS[0]?.id || null);

  useEffect(() => {
    if (activeTab === 'orders') loadOrders();
  }, [activeTab]);

  const loadOrders = async () => {
    setLoading(true);
    const data = await fetchAllOrders();
    setOrders(data);
    setLoading(false);
  };

  const saveLivePreview = () => {
    const fullConfig = { 
      ...config, 
      _products: registryProducts, 
      _variants: registryVariants, 
      _blocks: registryBlocks 
    };
    localStorage.setItem('CT_ADMIN_CONFIG_OVERRIDE', JSON.stringify(fullConfig));
    window.dispatchEvent(new Event('storage'));
    alert("DNA ATUALIZADO NO CACHE LOCAL. Verifique no site.");
  };

  const generateCoreFile = () => {
    const fileContent = `
/**
 * CLAUDIO TONELLI CORE REGISTRY - v14.5
 * GENERATED BY: ${profile.full_name} AT ${new Date().toLocaleString()}
 * REASON: SOVEREIGN FRONTEND BUILD
 */
import { Product, ProductVariant, ProductContentBlock, Insight } from '../types';

export type Language = 'pt' | 'en' | 'es';

export const SITE_CONFIG = ${JSON.stringify(config, null, 2)};
export const LOCAL_PRODUCTS: Product[] = ${JSON.stringify(registryProducts, null, 2)};
export const LOCAL_VARIANTS: Record<string, ProductVariant[]> = ${JSON.stringify(registryVariants, null, 2)};
export const LOCAL_BLOCKS: Record<string, ProductContentBlock[]> = ${JSON.stringify(registryBlocks, null, 2)};
export const LOCAL_INSIGHTS: Insight[] = ${JSON.stringify(LOCAL_INSIGHTS, null, 2)};
    `.trim();
    
    const blob = new Blob([fileContent], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'localRegistry.ts';
    a.click();
    alert("BUILD FINAL GERADO. Substitua o arquivo e faça o commit no GitHub.");
  };

  const handleNestedChange = (path: string, value: any) => {
    const keys = path.split('.');
    const newConfig = { ...config };
    let current: any = newConfig;
    for (let i = 0; i < keys.length - 1; i++) {
      if (!current[keys[i]]) current[keys[i]] = {};
      current = current[keys[i]];
    }
    current[keys[keys.length - 1]] = value;
    setConfig(newConfig);
  };

  if (!profile || profile.user_type !== 'admin') return null;

  return (
    <div className="fixed inset-0 z-[200] bg-[#010309]/98 backdrop-blur-3xl flex items-center justify-center p-4 lg:p-8 overflow-hidden">
      <div className="bg-[#02050c] border border-white/10 w-full max-w-[1750px] h-full rounded-[4rem] overflow-hidden flex flex-col lg:flex-row shadow-2xl transition-all">
        
        {/* Navigation Sidebar */}
        <div className="w-full lg:w-80 bg-[#010309] border-r border-white/5 p-10 flex flex-col gap-6 shrink-0">
          <div className="flex items-center gap-5 mb-8">
            <div className="w-14 h-14 bg-blue-600 rounded-3xl flex items-center justify-center font-bold text-white text-2xl shadow-xl shadow-blue-600/30">CT</div>
            <div className="flex flex-col">
              <span className="font-black text-[10px] uppercase tracking-[0.6em] text-white leading-none">Command Center</span>
              <span className="text-[7px] uppercase tracking-[0.3em] text-blue-500 font-bold mt-1">{ADMIN_VERSION}</span>
            </div>
          </div>
          
          <nav className="flex flex-col gap-2 flex-1 overflow-y-auto custom-scrollbar pr-2">
            {[
              { id: 'visual_dna', label: 'Visual DNA' },
              { id: 'sovereign_store', label: 'Sovereign Store' },
              { id: 'insights', label: 'Insights Registry' },
              { id: 'security_hub', label: 'Security Hub (DB)' },
              { id: 'orders', label: 'Sales Vault' },
              { id: 'hard_build', label: 'Hard Build' }
            ].map(tab => (
              <button 
                key={tab.id} 
                onClick={() => setActiveTab(tab.id as TabType)} 
                className={`px-6 py-4 rounded-xl text-[9px] font-black uppercase tracking-[0.3em] text-left transition-all border ${activeTab === tab.id ? 'bg-blue-600 text-white border-blue-400 shadow-2xl' : 'text-slate-600 border-transparent hover:text-white hover:bg-white/5'}`}
              >
                {tab.label}
              </button>
            ))}
          </nav>
          <button onClick={onClose} className="text-slate-700 hover:text-red-500 text-[10px] font-black uppercase tracking-[0.5em] p-6 border border-white/5 rounded-2xl transition-all">Sair do Core</button>
        </div>

        {/* Central Console */}
        <div className="flex-1 overflow-y-auto p-10 lg:p-20 bg-grid relative custom-scrollbar">
          <div className="max-w-6xl mx-auto pb-32">

            {activeTab === 'security_hub' && (
              <div className="space-y-16 animate-in fade-in duration-500">
                <header className="mb-12">
                  <h2 className="text-5xl font-serif text-white italic mb-4 tracking-tighter">Security Hub (DB Sensitive)</h2>
                  <p className="text-slate-500 text-sm font-light italic">Gestão de licenças e versões de APK - Conexão direta com Supabase.</p>
                </header>
                
                <section className="space-y-12">
                  <div>
                    <h3 className="text-xl text-white font-serif italic mb-6">Controle de Versões (V8 & Outros)</h3>
                    <AdminCrudSection 
                      tableName="app_versions" 
                      title="Versões de Software" 
                      fields={[
                        { key: 'app_name', label: 'Nome do Aplicativo (ex: v8_matrix)' },
                        { key: 'version_code', label: 'Código da Versão (ex: 6.0.0)' },
                        { key: 'download_url', label: 'URL Segura de Download' },
                        { key: 'is_forced', label: 'Update Obrigatório', type: 'toggle' },
                        { key: 'release_notes', label: 'Notas de Lançamento', type: 'textarea' }
                      ]} 
                      displayColumns={['app_name', 'version_code']} 
                    />
                  </div>

                  <div>
                    <h3 className="text-xl text-white font-serif italic mb-6">Monitor de Licenças Ativas</h3>
                    <AdminCrudSection 
                      tableName="user_products" 
                      title="Licenças de Usuários" 
                      fields={[
                        { key: 'user_id', label: 'ID do Usuário' },
                        { key: 'product_id', label: 'ID do Produto' },
                        { key: 'status', label: 'Status (active, trial, expired)' },
                        { key: 'expires_at', label: 'Expiração (ISO Date)' }
                      ]} 
                      displayColumns={['user_id', 'status']} 
                    />
                  </div>
                </section>
              </div>
            )}

            {activeTab === 'visual_dna' && (
              <div className="space-y-12 animate-in fade-in duration-500">
                <header className="flex justify-between items-end">
                  <h2 className="text-5xl font-serif text-white italic tracking-tighter">Visual DNA Forge</h2>
                  <button onClick={saveLivePreview} className="bg-blue-600 text-white px-10 py-4 rounded-2xl font-black text-[10px] uppercase tracking-widest shadow-2xl">Salvar DNA</button>
                </header>
                <div className="grid md:grid-cols-2 gap-10">
                  <section className="p-10 bg-slate-900/40 border border-white/5 rounded-[3rem] space-y-8">
                    <h3 className="text-[10px] font-black uppercase text-blue-500 tracking-[0.5em]">Estética Master</h3>
                    {['primary', 'bg_dark'].map(k => (
                      <div key={k} className="space-y-2">
                        <label className="text-[9px] font-black uppercase text-slate-500 tracking-widest">{k}</label>
                        <input type="text" value={config.theme[k]} onChange={e => handleNestedChange(`theme.${k}`, e.target.value)} className="w-full bg-black border border-white/5 rounded-xl p-4 text-white text-xs" />
                      </div>
                    ))}
                  </section>
                  <section className="p-10 bg-slate-900/40 border border-white/5 rounded-[3rem] space-y-8">
                    <h3 className="text-[10px] font-black uppercase text-blue-500 tracking-[0.5em]">Matrix Engine</h3>
                    {['matrix_speed', 'matrix_opacity'].map(k => (
                      <div key={k} className="space-y-2">
                        <label className="text-[9px] font-black uppercase text-slate-500 tracking-widest">{k}</label>
                        <input type="text" value={config.ux[k]} onChange={e => handleNestedChange(`ux.${k}`, e.target.value)} className="w-full bg-black border border-white/5 rounded-xl p-4 text-white text-xs" />
                      </div>
                    ))}
                  </section>
                </div>
              </div>
            )}

            {activeTab === 'sovereign_store' && (
              <div className="space-y-12 animate-in fade-in duration-500">
                <header className="mb-12">
                   <h2 className="text-5xl font-serif text-white italic tracking-tighter">Sovereign Store IDE</h2>
                   <p className="text-slate-500 text-sm italic">Edição visual de Ativos e Blocos Canvas para o localRegistry.ts</p>
                </header>
                <div className="grid lg:grid-cols-4 gap-12">
                   <div className="lg:col-span-1 space-y-4">
                      {registryProducts.map(p => (
                        <button key={p.id} onClick={() => setSelectedProductId(p.id)} className={`w-full p-6 rounded-[2rem] text-left border transition-all ${selectedProductId === p.id ? 'bg-blue-600 border-blue-400 text-white' : 'bg-slate-900/40 border-white/5 text-slate-500'}`}>
                           <div className="text-[11px] font-black uppercase truncate">{p.title}</div>
                        </button>
                      ))}
                   </div>
                   <div className="lg:col-span-3">
                      {selectedProductId && (
                        <section className="p-12 bg-slate-900/40 border border-white/5 rounded-[4rem] space-y-10">
                           <h4 className="text-xl text-white font-serif italic">Configuração Visual de Ativo</h4>
                           <div className="space-y-4">
                              <label className="text-[9px] font-black text-slate-500 uppercase">Título Público</label>
                              <input value={registryProducts.find(p => p.id === selectedProductId)?.title || ''} onChange={e => setRegistryProducts(prev => prev.map(p => p.id === selectedProductId ? {...p, title: e.target.value} : p))} className="w-full bg-black border border-white/5 rounded-2xl p-6 text-white text-sm" />
                           </div>
                           <button onClick={saveLivePreview} className="w-full py-5 bg-blue-600 text-white rounded-2xl font-black uppercase text-[10px] tracking-[0.4em]">Sincronizar Preview</button>
                        </section>
                      )}
                   </div>
                </div>
              </div>
            )}

            {activeTab === 'hard_build' && (
              <div className="p-20 bg-blue-600/5 border border-blue-600/10 rounded-[4rem] text-center space-y-10 animate-in zoom-in-95 duration-700">
                <h3 className="text-4xl font-serif text-white italic tracking-tighter">Consolidar DNA Soberano v14.5</h3>
                <p className="text-slate-500 text-sm max-w-xl mx-auto italic font-light leading-relaxed">
                  Gere o arquivo `localRegistry.ts` definitivo. Este ato transfere todas as suas edições visuais da Store e do DNA para o código-fonte imutável.
                </p>
                <button onClick={generateCoreFile} className="px-16 py-7 bg-white text-brand-navy rounded-[2.5rem] font-black uppercase tracking-[0.4em] text-[11px] hover:bg-blue-600 hover:text-white transition-all shadow-2xl">GERAR BUILD REGISTRY.TS</button>
              </div>
            )}

            {activeTab === 'orders' && (
              <div className="space-y-8">
                <h2 className="text-5xl font-serif text-white italic tracking-tighter">Sales Vault</h2>
                {orders.map(o => (
                  <div key={o.id} className="bg-slate-900/40 p-8 rounded-[3rem] border border-white/5 flex items-center justify-between">
                    <div className="flex items-center gap-6">
                       <div className="w-12 h-12 bg-slate-950 rounded-2xl flex items-center justify-center text-slate-600 font-bold border border-white/5 uppercase">{o.profiles?.full_name?.charAt(0)}</div>
                       <div>
                          <span className="text-xl font-serif text-white italic">{o.profiles?.full_name}</span>
                          <div className="text-[9px] font-black text-blue-500 uppercase tracking-widest">R$ {o.amount.toLocaleString('pt-BR')} — {o.status}</div>
                       </div>
                    </div>
                  </div>
                ))}
              </div>
            )}

          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminDashboard;